import cv2
import funcs
import numpy as np

win_list = [3, 5, 7]
blur_patch = np.ones((6, 6), np.uint8)

cat = cv2.imread('cat.jpg')
cat_rgb = funcs.segmentation_rgb(cat, 6, 1, invert=[1, 1, 0], tag=False)
cat_rgb = cv2.dilate(cat_rgb, blur_patch)
cat_rgb = cv2.erode(cat_rgb, blur_patch)
cv2.imwrite('cat_rgb.jpg', cat_rgb)
cat_rgb_contour = funcs.find_contour(cat_rgb)
cv2.imwrite('cat_rgb_contour.jpg', cat_rgb_contour)
cat_rgb_contour_merge = funcs.draw_contour(cat, cat_rgb_contour)
cv2.imwrite('cat_rgb_contour_merge.jpg', cat_rgb_contour_merge)

# fox = cv2.imread('fox.jpg')
# fox_rgb = funcs.segmentation_rgb(fox, 8, 2, invert=[0, 1, 0], tag=False)
# fox_rgb = cv2.dilate(fox_rgb, blur_patch)
# fox_rgb = cv2.erode(fox_rgb, blur_patch)
# cv2.imwrite('fox_rgb.jpg', fox_rgb)
# fox_rgb_contour = funcs.find_contour(fox_rgb)
# cv2.imwrite('fox_rgb_contour.jpg', fox_rgb_contour)
# fox_rgb_contour_merge = funcs.draw_contour(fox, fox_rgb_contour)
# cv2.imwrite('fox_rgb_contour_merge.jpg', fox_rgb_contour_merge)
#
# pigeon = cv2.imread('pigeon.jpeg')
# pigeon_rgb = funcs.segmentation_rgb(pigeon, 13, 3, tag=False)
# pigeon_rgb = cv2.dilate(pigeon_rgb, blur_patch)
# pigeon_rgb = cv2.erode(pigeon_rgb, blur_patch)
# cv2.imwrite('pigeon_rgb.jpg', pigeon_rgb)
# pigeon_rgb_contour = funcs.find_contour(pigeon_rgb)
# cv2.imwrite('pigeon_rgb_contour.jpg', pigeon_rgb_contour)
# pigeon_rgb_merge = funcs.draw_contour(pigeon, pigeon_rgb_contour)
# cv2.imwrite('pigeon_rgb_merge.jpg', pigeon_rgb_merge)
#
# blur_patch = np.ones((8, 8), np.uint8)
#
# temp_cat = funcs.texture_segmentation(cat, win_list, 1)
# cat_texture = funcs.segmentation_rgb(temp_cat, 3, img_num=4, tag=False)
# cat_texture = cv2.dilate(cat_texture, blur_patch)
# cat_texture = cv2.erode(cat_texture, blur_patch)
# cv2.imwrite('cat_texture.jpg', cat_texture)
# cat_texture_contour = funcs.find_contour(cat_texture)
# cv2.imwrite('cat_texture_contour.jpg', cat_texture_contour)
# cat_texture_merge = funcs.draw_contour(cat, cat_texture_contour)
# cv2.imwrite('cat_texture_merge.jpg', cat_texture_merge)
#
# temp_fox = funcs.texture_segmentation(fox, win_list, 2)
# fox_texture = funcs.segmentation_rgb(temp_fox, 4, img_num=5, tag=False)
# fox_texture = cv2.dilate(fox_texture, blur_patch)
# fox_texture = cv2.erode(fox_texture, blur_patch)
# cv2.imwrite('fox_texture.jpg', fox_texture)
# fox_texture_contour = funcs.find_contour(fox_texture)
# cv2.imwrite('fox_texture_contour.jpg', fox_texture_contour)
# fox_texture_merge = funcs.draw_contour(fox, fox_texture_contour)
# cv2.imwrite('fox_texture_merge.jpg', fox_texture_merge)
#
# temp_pigeon = funcs.texture_segmentation(pigeon, win_list, 3)
# pigeon_texture = funcs.segmentation_rgb(temp_pigeon, 7, img_num=6, invert=[1, 1, 1], tag=False)
# pigeon_texture = cv2.dilate(pigeon_texture, np.ones((3, 3), np.uint8))
# pigeon_texture = cv2.erode(pigeon_texture, np.ones((3, 3), np.uint8))
# cv2.imwrite('pigeon_texture.jpg', pigeon_texture)
# pigeon_texture_contour = funcs.find_contour(pigeon_texture)
# cv2.imwrite('pigeon_texture_contour.jpg', pigeon_texture_contour)
# pigeon_texture_merge = funcs.draw_contour(pigeon, pigeon_texture_contour)
# cv2.imwrite('pigeon_texture_merge.jpg', pigeon_texture_merge)
